.MODEL SMALL
.STACK 64

.DATA
STRING DB "My name is Ayush Bhandari$"
LEN DW $-STRING

.CODE
	MOV AX, @DATA
	MOV DS, AX

	;SETTING VIDEO MODE TO 80x24
	MOV AH, 00H 
	MOV AL, 03H
	INT 10H
	
	;CLEAR THE SCREEN
	MOV AH, 06H
	MOV AL, 0 ; CLEAR THE SCREEN
	INT 10H
	
	;PLACE CURSOR AT CENTER OF THE SCREEN
	MOV AH, 02H 
	MOV DH, 12 ; ROW NUMBER
	MOV DL, 40 ; COLUMN NUMBER
	INT 10H
	
	;CHANGE COLOR OF THE SCREEN
	MOV AH, 06H
	MOV BH, 07H ; CHOOSE COLOR OF THE SCREEN
	MOV CX, 0000H
	MOV DX, 2479H
	INT 10H
	
	;DISPLAY A STRING
	MOV AH, 09H
	MOV DX, OFFSET STRING
	INT 21H

	;PLACE CURSOR AT CENTER OF THE SCREEN
	MOV AX, 0000
	MOV BX, 0000
	MOV AH, 02H 
	MOV DH, 13 ; ROW NUMBER
	MOV DL, 40 ; COLUMN NUMBER
	INT 10H

	;REVERSE THE GIVEN STRING
	LEA BX, STRING
	MOV SI, LEN
	DEC SI
	DEC SI
	MOV CX, LEN
	DEC CX
	L1: MOV AH, 02H
	MOV DL, BYTE PTR[BX+SI]
	INT 21H
	DEC BX
	LOOP L1
	

	;PLACE CURSOR AT CENTER OF THE SCREEN
	MOV AX, 0000
	MOV BX, 0000
	MOV AH, 02H 
	MOV DH, 14 ; ROW NUMBER
	MOV DL, 40 ; COLUMN NUMBER
	INT 10H
	
	;DISPLAY THE LENGTH OF THE STRING
	MOV CX, LEN
	MOV BL, 0AH
	MOV AX, CX
	DEC AX
	
	DIV BL ; STORES QUOTIENT IN AL AND REMAINDER IN AH
	MOV DH, AH ; QUOTIENT STORED IN DH
	ADD AL, 48 ;CONVERT ASCII TO NUMBER
	
	MOV AH, 02H
	MOV DL, AL
	INT 21H
	
	MOV AL, DH ; STORES 8 IN AL
	ADD AL, 48 ;CONVERT ASCII TO NUMBER

	MOV AH, 02H
	MOV DL, AL
	INT 21H
	
	MOV AH, 4CH
	INT 21H
	END
	
	
